name: Build

on: [push, pull_request]

jobs:
  build-on-linux-with-jdk-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'maven'

      - name: Build and test
        run: mvn clean verify --no-transfer-progress
